### ISSUE TITLE
使用Docker启动Cassandra报错

### ISSUE THREAD

**Issue by BigDEM0N** [BigDEM0N/taco-cloud#1]
docker-compose.yml文件如下
```yaml
version: '3'

services:
  database:
    image: cassandra
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
      - CASSANDRA_SEEDS=seed1,seed2
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_KEYSPACE=tacocloud
      - CASSANDRA_SCHEMA_ACTION=recreate
      - JVM_OPTS=-XX:+UseG1GC
    ports:
      - "9042:9042"


networks:    # 定义网络
  tacocloud-network:
    driver: bridge
```

使用命令`docker compose up -d`启动报错
`OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
`
